# Generated by Django 5.0.6 on 2024-07-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0002_remove_message_file_messagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
