# Generated by Django 5.0.6 on 2024-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0004_messagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
