# Generated by Django 5.0.6 on 2024-07-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0005_category_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
